CREATE SEQUENCE sq_tipo_titulo
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_local
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_socio
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_local_socio
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_medico
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_conta_receber
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_mensalidade
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_caixa
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_convidado
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_dependente
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_entrada_saida
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE sq_exame_medico
  START WITH 1
  INCREMENT BY 1;